[package]
name = "edilithium"
version = "0.1.0"
edition = "2024"
authors = ["Morgane Guerreau"]
license = "MIT"

[dependencies]
curve25519-dalek = { version = "5.0", features = ["rand_core"]}
ed25519-dalek = { version = "3.0", features = ["rand_core"]}
elliptic-curve = { version = "0.14", features = ["sec1"] }
sha3 = "0.11"
sha2 = "0.11"
ml-dsa = "0.1"
hybrid-array = "0.4"
getrandom = { version = "0.4", features = ["sys_rng"] }
rand_core = "0.10"
digest = "0.11"
signature = "3.0"
keccak = "0.2"
crypto-common = "0.2"
crypto-bigint = "0.7"

[dev-dependencies]
p256 = "0.14"
p384 = "0.14"
p521 = "0.14"


